# Generated by Django 4.2.3 on 2024-04-06 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
